# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguraton: 'Release'

steps:

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/*Test/*.csproj'
    arguments: '--configuration $(buildConfiguraton)'

- script: dotnet build --configuration $(buildConfiguraton)
  displayName: 'dotnet build $(buildConfiguraton)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet publish --configuration $(buildConfiguraton) --output $(Build.ArtfactStagingDirectory)'
  inputs:
    command: publish
    publishWebProjects: false
    projects: 'src/SimpleAPI/SimpleAPI.csproj'
    arguments: '--configuration $(buildConfiguraton) --output $(Build.ArtfactStagingDirectory)'
    zipAfterPubish: true

- task: PublishBuildArtifacts@1
  displayName: 'publish artifacts'